# Generated by Django 5.0.3 on 2024-04-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_index_category_index_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='image1',
            field=models.ImageField(default='', upload_to='static/admin/img/'),
        ),
        migrations.AddField(
            model_name='index',
            name='image2',
            field=models.ImageField(default='', upload_to='static/admin/img/'),
        ),
        migrations.AlterField(
            model_name='index',
            name='image',
            field=models.ImageField(default='', upload_to='static/admin/img/'),
        ),
    ]
