# Generated by Django 5.0.3 on 2024-04-11 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_customer_detail_guide_detail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='guide_detail',
        ),
    ]
