# Generated by Django 5.0.3 on 2024-04-11 07:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_guide_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide_detail',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
