# Generated by Django 5.0.3 on 2024-04-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_guide_detail_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_detail',
            name='placename',
            field=models.CharField(default='', max_length=50),
        ),
    ]
