# Generated by Django 5.0.3 on 2024-04-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_customer_detail_placename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='id',
        ),
        migrations.AddField(
            model_name='index',
            name='msg_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
