# Generated by Django 5.0.3 on 2024-04-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_index_msg_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='msg_id',
        ),
        migrations.AddField(
            model_name='index',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
