# Generated by Django 5.0.3 on 2024-04-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_index_msg_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_detail',
            name='placename',
        ),
        migrations.AddField(
            model_name='customer_detail',
            name='Customer_id',
            field=models.CharField(default='', max_length=10000000),
        ),
    ]
