# Generated by Django 5.0.3 on 2024-04-27 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_index_rating_remove_index_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='user',
        ),
    ]
